repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.5.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.3"]
        description: "Format, organize imports, lint, and apply safe fixes to the committed files"
